version: '3.8'

services:

  server:
    image: nginx:alpine
    restart: always
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./public:/code/public
    ports:
      - '80:80'
      - '443:443'

  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
#    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data

  web:
    build:
      context: .
    env_file:
      - .env
#    container_name: gramone
    command: sh -c "/code/run.sh"
    ports:
      - '8000:8000'
    depends_on:
      - postgres