"""empty message

Revision ID: 79b3224c0081
Revises: 572dcd23b688
Create Date: 2023-04-21 10:03:01.573656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79b3224c0081'
down_revision = '572dcd23b688'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('username', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_admin_user_username'), 'admin_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_user_username'), table_name='admin_user')
    op.drop_column('admin_user', 'username')
    # ### end Alembic commands ###
